#!/usr/bin/env python3
#
# remt - reMarkable tablet tools
#
# Copyright (C) 2018 by Artur Wroblewski <wrobell@riseup.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import argparse
from cytoolz.functoolz import pipe
from cytoolz.curried import map

import remt

parser = argparse.ArgumentParser(description="""\
Convert reMarkable table lines file to a PDF file. Optionally, annotate a
PDF file with the lines file.
""")

parser.add_argument('input', help='reMarkable table lines file')
parser.add_argument(
    'in_pdf',
    nargs='?',
    help='PDF file being annotated with lines file'
)
parser.add_argument('output', help='PDF output file')

args = parser.parse_args()

with open(args.input, 'rb') as f, \
        remt.draw_context(args.output) as ctx:

    items = pipe(f, remt.parse, map(remt.reset_style))
    for item in items:
        remt.draw(item, ctx)

# vim: sw=4:et:ai
